-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mike_rs]: type definitions
module
public import Aeneas
public import MikeRs.TypesExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace mike_rs

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 768:0-768:37
    Name pattern: [core::ops::arith::AddAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::SubAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 839:0-839:37
    Name pattern: [core::ops::arith::SubAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::SubAssign"]
structure core.ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::MulAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 901:0-901:37
    Name pattern: [core::ops::arith::MulAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::MulAssign"]
structure core.ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::DivAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 963:0-963:37
    Name pattern: [core::ops::arith::DivAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::DivAssign"]
structure core.ops.arith.DivAssign (Self : Type) (Rhs : Type) where
  div_assign : Self → Rhs → Result Self

/-- [typenum::uint::UTerm]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 50:0-50:16
    Name pattern: [typenum::uint::UTerm]
    Visibility: public -/
@[reducible, rust_type "typenum::uint::UTerm"]
def typenum.uint.UTerm := Unit

/-- [typenum::bit::B1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 33:0-33:13
    Name pattern: [typenum::bit::B1]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B1"]
def typenum.bit.B1 := Unit

/-- [typenum::bit::B0]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 20:0-20:13
    Name pattern: [typenum::bit::B0]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B0"]
def typenum.bit.B0 := Unit

/-- Trait declaration: [typenum::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 154:4-154:20
    Name pattern: [typenum::sealed::Sealed]
    Visibility: public -/
@[rust_trait "typenum::sealed::Sealed"]
structure typenum.sealed.Sealed (Self : Type) where

/-- Trait declaration: [typenum::marker_traits::Unsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 59:0-59:53
    Name pattern: [typenum::marker_traits::Unsigned]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Unsigned"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "U16", "U32", "U64", "USIZE", "I8", "I16", "I32", "I64", "ISIZE"])]
structure typenum.marker_traits.Unsigned (Self : Type) where
  U8 : Result Std.U8
  U16 : Result Std.U16
  U32 : Result Std.U32
  U64 : Result Std.U64
  USIZE : Result Std.Usize
  I8 : Result Std.I8
  I16 : Result Std.I16
  I32 : Result Std.I32
  I64 : Result Std.I64
  ISIZE : Result Std.Isize
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  to_u8 : Result Std.U8
  to_u16 : Result Std.U16
  to_u32 : Result Std.U32
  to_u64 : Result Std.U64
  to_usize : Result Std.Usize
  to_i8 : Result Std.I8
  to_i16 : Result Std.I16
  to_i32 : Result Std.I32
  to_i64 : Result Std.I64
  to_isize : Result Std.Isize

/-- Trait declaration: [typenum::marker_traits::Bit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 35:0-35:48
    Name pattern: [typenum::marker_traits::Bit]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Bit"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "BOOL"])]
structure typenum.marker_traits.Bit (Self : Type) where
  U8 : Result Std.U8
  BOOL : Result Bool
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  new : Result Self
  to_u8 : Result Std.U8
  to_bool : Result Bool

/-- Trait declaration: [generic_array::ArrayLength]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 112:0-112:41
    Name pattern: [generic_array::ArrayLength]
    Visibility: public -/
@[rust_trait "generic_array::ArrayLength"
  (parentClauses := ["typenummarker_traitsUnsignedInst"])]
structure generic_array.ArrayLength (Self : Type) (T : Type) (Self_ArrayType :
  Type) where
  typenummarker_traitsUnsignedInst : typenum.marker_traits.Unsigned Self

/-- Trait declaration: [crypto_common::KeySizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 80:0-80:21
    Name pattern: [crypto_common::KeySizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::KeySizeUser"
  (parentClauses := ["generic_arrayArrayLengthSelf_KeySizeU8Self_Clause0_ArrayTypeInst"])]
structure crypto_common.KeySizeUser (Self : Type) (Self_KeySize : Type)
  (Self_Clause0_ArrayType : Type) where
  generic_arrayArrayLengthSelf_KeySizeU8Self_Clause0_ArrayTypeInst :
    generic_array.ArrayLength Self_KeySize Std.U8 Self_Clause0_ArrayType

/-- Trait declaration: [crypto_common::KeyInit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 124:0-124:38
    Name pattern: [crypto_common::KeyInit]
    Visibility: public -/
@[rust_trait "crypto_common::KeyInit" (parentClauses := ["KeySizeUserInst"])]
structure crypto_common.KeyInit (Self : Type) (Self_Clause0_KeySize : Type)
  (Self_Clause0_Clause0_ArrayType : Type) where
  KeySizeUserInst : crypto_common.KeySizeUser Self Self_Clause0_KeySize
    Self_Clause0_Clause0_ArrayType
  new : generic_array.GenericArray Std.U8 Self_Clause0_KeySize
    Self_Clause0_Clause0_ArrayType → Result Self

/-- Trait declaration: [crypto_common::BlockSizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 42:0-42:23
    Name pattern: [crypto_common::BlockSizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::BlockSizeUser"
  (parentClauses := ["generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst"])]
structure crypto_common.BlockSizeUser (Self : Type) (Self_BlockSize : Type)
  (Self_Clause0_ArrayType : Type) where
  generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst :
    generic_array.ArrayLength Self_BlockSize Std.U8 Self_Clause0_ArrayType

/-- Trait declaration: [cipher::block::BlockCipher]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/block.rs', lines 26:0-26:36
    Name pattern: [cipher::block::BlockCipher]
    Visibility: public -/
@[rust_trait "cipher::block::BlockCipher"
  (parentClauses := ["crypto_commonBlockSizeUserInst"])]
structure cipher.block.BlockCipher (Self : Type) (Self_Clause0_BlockSize :
  Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType

/-- Trait declaration: [crypto_common::ParBlocksSizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 61:0-61:42
    Name pattern: [crypto_common::ParBlocksSizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::ParBlocksSizeUser"
  (parentClauses := ["BlockSizeUserInst", "generic_arrayArrayLengthSelf_ParBlocksSizeGenericArrayU8Self_Clause0_BlockSizeSelf_Clause0_Clause0_ArrayTypeSelf_Clause1_ArrayTypeInst"])]
structure crypto_common.ParBlocksSizeUser (Self : Type) (Self_ParBlocksSize :
  Type) (Self_Clause0_BlockSize : Type) (Self_Clause0_Clause0_ArrayType : Type)
  (Self_Clause1_ArrayType : Type) where
  BlockSizeUserInst : crypto_common.BlockSizeUser Self Self_Clause0_BlockSize
    Self_Clause0_Clause0_ArrayType
  generic_arrayArrayLengthSelf_ParBlocksSizeGenericArrayU8Self_Clause0_BlockSizeSelf_Clause0_Clause0_ArrayTypeSelf_Clause1_ArrayTypeInst
    : generic_array.ArrayLength Self_ParBlocksSize (generic_array.GenericArray
    Std.U8 Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType)
    Self_Clause1_ArrayType

/-- Trait declaration: [cipher::block::BlockBackend]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/block.rs', lines 29:0-29:41
    Name pattern: [cipher::block::BlockBackend]
    Visibility: public -/
@[rust_trait "cipher::block::BlockBackend"
  (parentClauses := ["crypto_commonParBlocksSizeUserInst"])]
structure cipher.block.BlockBackend (Self : Type) (Self_Clause0_ParBlocksSize :
  Type) (Self_Clause0_Clause0_BlockSize : Type)
  (Self_Clause0_Clause0_Clause0_ArrayType : Type)
  (Self_Clause0_Clause1_ArrayType : Type) where
  crypto_commonParBlocksSizeUserInst : crypto_common.ParBlocksSizeUser Self
    Self_Clause0_ParBlocksSize Self_Clause0_Clause0_BlockSize
    Self_Clause0_Clause0_Clause0_ArrayType Self_Clause0_Clause1_ArrayType
  proc_block : Self → inout.inout.InOut (generic_array.GenericArray Std.U8
    Self_Clause0_Clause0_BlockSize Self_Clause0_Clause0_Clause0_ArrayType) →
    Result (Self × (inout.inout.InOut (generic_array.GenericArray Std.U8
    Self_Clause0_Clause0_BlockSize Self_Clause0_Clause0_Clause0_ArrayType)))

/-- Trait declaration: [cipher::block::BlockClosure]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/block.rs', lines 74:0-74:37
    Name pattern: [cipher::block::BlockClosure]
    Visibility: public -/
@[rust_trait "cipher::block::BlockClosure"
  (parentClauses := ["crypto_commonBlockSizeUserInst"])]
structure cipher.block.BlockClosure (Self : Type) (Self_Clause0_BlockSize :
  Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType
  call : forall {B : Type} {Clause0_Clause0_ParBlocksSize : Type}
    {Clause0_Clause0_Clause0_Clause0_ArrayType : Type}
    {Clause0_Clause0_Clause1_ArrayType : Type} (BlockBackendInst :
    cipher.block.BlockBackend B Clause0_Clause0_ParBlocksSize
    Self_Clause0_BlockSize Clause0_Clause0_Clause0_Clause0_ArrayType
    Clause0_Clause0_Clause1_ArrayType), Self → B → Result B

/-- Trait declaration: [cipher::block::BlockEncrypt]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cipher-0.4.4/src/block.rs', lines 80:0-80:45
    Name pattern: [cipher::block::BlockEncrypt]
    Visibility: public -/
@[rust_trait "cipher::block::BlockEncrypt"
  (parentClauses := ["crypto_commonBlockSizeUserInst"])]
structure cipher.block.BlockEncrypt (Self : Type) (Self_Clause0_BlockSize :
  Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType
  encrypt_with_backend : forall {T1 : Type} {Clause0_Clause0_Clause0_ArrayType
    : Type} (BlockClosureInst : cipher.block.BlockClosure T1
    Self_Clause0_BlockSize Clause0_Clause0_Clause0_ArrayType), Self → T1 →
    Result Unit

/-- Trait declaration: [fp2::traits::Fq]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/traits/mod.rs', lines 13:0-28:15
    Name pattern: [fp2::traits::Fq]
    Visibility: public -/
@[rust_trait "fp2::traits::Fq"
  (parentClauses := ["coremarkerCopyInst", "coreopsarithNegInst", "coreopsarithAddInst", "coreopsarithAddAssignInst", "coreopsarithSubInst", "coreopsarithSubAssignInst", "coreopsarithMulInst", "coreopsarithMulAssignInst", "coreopsarithDivInst", "coreopsarithDivAssignInst", "corefmtDisplayInst", "coreconvertFromSelfU32Inst", "coreconvertFromSelfU64Inst", "coreconvertFromSelfI32Inst", "coreconvertFromSelfI64Inst", "coremarkerCopyInst1", "coreconvertAsRefSelf_EncodedSliceU8Inst", "coreconvertAsMutSelf_EncodedSliceU8Inst"])
  (consts := ["ENCODED_LENGTH", "ZERO", "ONE", "TWO", "THREE", "FOUR", "MINUS_ONE"])]
structure fp2.traits.Fq (Self : Type) (Self_Encoded : Type) where
  ENCODED_LENGTH : Result Std.Usize
  ZERO : Result Self
  ONE : Result Self
  TWO : Result Self
  THREE : Result Self
  FOUR : Result Self
  MINUS_ONE : Result Self
  coremarkerCopyInst : core.marker.Copy Self
  coreopsarithNegInst : core.ops.arith.Neg Self Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self
  coreopsarithAddAssignInst : core.ops.arith.AddAssign Self Self
  coreopsarithSubInst : core.ops.arith.Sub Self Self Self
  coreopsarithSubAssignInst : core.ops.arith.SubAssign Self Self
  coreopsarithMulInst : core.ops.arith.Mul Self Self Self
  coreopsarithMulAssignInst : core.ops.arith.MulAssign Self Self
  coreopsarithDivInst : core.ops.arith.Div Self Self Self
  coreopsarithDivAssignInst : core.ops.arith.DivAssign Self Self
  corefmtDisplayInst : core.fmt.Display Self
  coreconvertFromSelfU32Inst : core.convert.From Self Std.U32
  coreconvertFromSelfU64Inst : core.convert.From Self Std.U64
  coreconvertFromSelfI32Inst : core.convert.From Self Std.I32
  coreconvertFromSelfI64Inst : core.convert.From Self Std.I64
  coremarkerCopyInst1 : core.marker.Copy Self_Encoded
  coreconvertAsRefSelf_EncodedSliceU8Inst : core.convert.AsRef Self_Encoded
    (Slice Std.U8)
  coreconvertAsMutSelf_EncodedSliceU8Inst : core.convert.AsMut Self_Encoded
    (Slice Std.U8)
  is_zero : Self → Result Std.U32
  equals : Self → Self → Result Std.U32
  set_neg : Self → Result Self
  set_half : Self → Result Self
  set_mul2 : Self → Result Self
  set_mul3 : Self → Result Self
  set_mul4 : Self → Result Self
  set_mul8 : Self → Result Self
  set_mul_small : Self → Std.I32 → Result Self
  set_square : Self → Result Self
  set_n_square : Self → Std.U32 → Result Self
  set_invert : Self → Result Self
  set_sqrt : Self → Result (Std.U32 × Self)
  half : Self → Result Self
  mul2 : Self → Result Self
  mul3 : Self → Result Self
  mul4 : Self → Result Self
  mul8 : Self → Result Self
  mul_small : Self → Std.I32 → Result Self
  square : Self → Result Self
  n_square : Self → Std.U32 → Result Self
  invert : Self → Result Self
  sqrt : Self → Result (Self × Std.U32)
  legendre : Self → Result Std.I32
  is_square : Self → Result Std.U32
  batch_invert : Slice Self → Result (Slice Self)
  set_select : Self → Self → Self → Std.U32 → Result Self
  set_cond : Self → Self → Std.U32 → Result Self
  set_cond_neg : Self → Std.U32 → Result Self
  select : Self → Self → Std.U32 → Result Self
  cond_swap : Self → Self → Std.U32 → Result (Self × Self)
  encode : Self → Result Self_Encoded
  decode : Slice Std.U8 → Result (Self × Std.U32)
  decode_reduce : Slice Std.U8 → Result Self
  hashcode : Self → Result Std.U64

/-- Trait declaration: [fp2::traits::FqRoots]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/traits/mod.rs', lines 197:0-197:21
    Name pattern: [fp2::traits::FqRoots]
    Visibility: public -/
@[rust_trait "fp2::traits::FqRoots" (parentClauses := ["FqInst"])]
structure fp2.traits.FqRoots (Self : Type) (Self_Clause0_Encoded : Type) where
  FqInst : fp2.traits.Fq Self Self_Clause0_Encoded
  set_fourth_root : Self → Result (Std.U32 × Self)
  fourth_root : Self → Result (Self × Std.U32)

/-- Trait declaration: [fp2::traits::FqExp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/traits/mod.rs', lines 214:0-214:19
    Name pattern: [fp2::traits::FqExp]
    Visibility: public -/
@[rust_trait "fp2::traits::FqExp" (parentClauses := ["FqInst"])]
structure fp2.traits.FqExp (Self : Type) (Self_Clause0_Encoded : Type) where
  FqInst : fp2.traits.Fq Self Self_Clause0_Encoded
  set_pow : Self → Slice Std.U8 → Std.Usize → Result Self
  set_pow_ext : Self → Slice Std.U8 → Std.Usize → Std.Usize → Result
    Self
  set_pow_u64 : Self → Std.U64 → Std.Usize → Result Self
  set_pow_pubexp : Self → Slice Std.U64 → Result Self
  set_pow_u64_vartime : Self → Std.U64 → Result Self
  pow : Self → Slice Std.U8 → Std.Usize → Result Self
  pow_ext : Self → Slice Std.U8 → Std.Usize → Std.Usize → Result Self
  pow_u64 : Self → Std.U64 → Std.Usize → Result Self
  pow_u64_vartime : Self → Std.U64 → Result Self
  pow_pubexp : Self → Slice Std.U64 → Result Self

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.5/src/lib.rs', lines 130:0-130:17
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::CryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.5/src/lib.rs', lines 204:0-204:28
    Name pattern: [rand_core::CryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::CryptoRng" (parentClauses := ["RngCoreInst"])]
structure rand_core.CryptoRng (Self : Type) where
  RngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [fp2::traits::FqRnd]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/traits/mod.rs', lines 266:0-266:19
    Name pattern: [fp2::traits::FqRnd]
    Visibility: public -/
@[rust_trait "fp2::traits::FqRnd" (parentClauses := ["FqInst"])]
structure fp2.traits.FqRnd (Self : Type) (Self_Clause0_Encoded : Type) where
  FqInst : fp2.traits.Fq Self Self_Clause0_Encoded
  set_rand : forall {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R)
    (rand_coreRngCoreInst : rand_core.RngCore R), Self → R → Result (Self
    × R)
  rand : forall {R : Type} (rand_coreCryptoRngInst : rand_core.CryptoRng R)
    (rand_coreRngCoreInst : rand_core.RngCore R), R → Result (Self × R)

/-- Trait declaration: [fp2::traits::Fp2]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/traits/mod.rs', lines 278:0-278:43
    Name pattern: [fp2::traits::Fp2]
    Visibility: public -/
@[rust_trait "fp2::traits::Fp2"
  (parentClauses := ["FqInst", "FqExpInst", "FqRootsInst", "FqRndInst", "FqInst1"])
  (consts := ["ZETA", "MINUS_ZETA"])]
structure fp2.traits.Fp2 (Self : Type) (Self_BaseField : Type)
  (Self_Clause0_Encoded : Type) (Self_Clause1_Clause0_Encoded : Type)
  (Self_Clause2_Clause0_Encoded : Type) (Self_Clause3_Clause0_Encoded : Type)
  (Self_Clause4_Encoded : Type) where
  ZETA : Result Self
  MINUS_ZETA : Result Self
  FqInst : fp2.traits.Fq Self Self_Clause0_Encoded
  FqExpInst : fp2.traits.FqExp Self Self_Clause1_Clause0_Encoded
  FqRootsInst : fp2.traits.FqRoots Self Self_Clause2_Clause0_Encoded
  FqRndInst : fp2.traits.FqRnd Self Self_Clause3_Clause0_Encoded
  FqInst1 : fp2.traits.Fq Self_BaseField Self_Clause4_Encoded
  set_x0_small : Self → Std.I32 → Result Self
  set_x1_small : Self → Std.I32 → Result Self
  from_i32_pair : Std.I32 → Std.I32 → Result Self
  from_u32_pair : Std.U32 → Std.U32 → Result Self
  from_i64_pair : Std.I64 → Std.I64 → Result Self
  from_u64_pair : Std.U64 → Std.U64 → Result Self
  x0 : Self → Result Self_BaseField
  x1 : Self → Result Self_BaseField
  xi : Self → Result (Self_BaseField × Self_BaseField)
  set_conjugate : Self → Result Self
  conjugate : Self → Result Self
  is_square_base_field : Self → Result Std.U32
  precompute_dlp_tables : Self → Std.Usize → Result ((alloc.vec.Vec
    Std.Usize) × (alloc.vec.Vec Self) × Std.U32)
  solve_dlp_2e : Self → Self → Std.Usize → Option ((alloc.vec.Vec
    Std.Usize) × (alloc.vec.Vec Self)) → Result ((alloc.vec.Vec Std.U8) ×
    Std.U32)

/-- Trait declaration: [rand_core::TryRngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.5/src/lib.rs', lines 220:0-220:20
    Name pattern: [rand_core::TryRngCore]
    Visibility: public -/
@[rust_trait "rand_core::TryRngCore"
  (parentClauses := ["corefmtDebugInst", "corefmtDisplayInst"])]
structure rand_core.TryRngCore (Self : Type) (Self_Error : Type) where
  corefmtDebugInst : core.fmt.Debug Self_Error
  corefmtDisplayInst : core.fmt.Display Self_Error
  try_next_u32 : Self → Result ((core.result.Result Std.U32 Self_Error) ×
    Self)
  try_next_u64 : Self → Result ((core.result.Result Std.U64 Self_Error) ×
    Self)
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    Self_Error) × Self × (Slice Std.U8))

/-- [nist_drbg_rs::SeedError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nist-drbg-rs-0.1.3/src/lib.rs', lines 62:0-62:18
    Name pattern: [nist_drbg_rs::SeedError]
    Visibility: public -/
@[discriminant isize, rust_type "nist_drbg_rs::SeedError"]
inductive nist_drbg_rs.SeedError where
| InsufficientEntropy : nist_drbg_rs.SeedError
| LengthError : Std.U64 → Std.U64 → nist_drbg_rs.SeedError
| IncorrectLength : Std.U64 → Std.U64 → nist_drbg_rs.SeedError
| CounterExhausted : nist_drbg_rs.SeedError

/-- Trait declaration: [nist_drbg_rs::ctr::CtrModeLimits]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nist-drbg-rs-0.1.3/src/ctr.rs', lines 597:0-597:23
    Name pattern: [nist_drbg_rs::ctr::CtrModeLimits]
    Visibility: public -/
@[rust_trait "nist_drbg_rs::ctr::CtrModeLimits"
  (consts := ["DEFAULT_RESEED_INTERVAL", "MAX_RESEED_INTERVAL", "MAX_OUTPUT"])]
structure nist_drbg_rs.ctr.CtrModeLimits (Self : Type) where
  DEFAULT_RESEED_INTERVAL : Result Std.U64
  MAX_RESEED_INTERVAL : Result Std.U64
  MAX_OUTPUT : Result Std.U64

/-- Trait declaration: [rand_core::TryCryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.5/src/lib.rs', lines 291:0-291:34
    Name pattern: [rand_core::TryCryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::TryCryptoRng" (parentClauses := ["TryRngCoreInst"])]
structure rand_core.TryCryptoRng (Self : Type) (Self_Clause0_Error : Type)
  where
  TryRngCoreInst : rand_core.TryRngCore Self Self_Clause0_Error

/-- [nist_drbg_rs::ctr::AesLimits]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nist-drbg-rs-0.1.3/src/ctr.rs', lines 608:0-608:20
    Name pattern: [nist_drbg_rs::ctr::AesLimits]
    Visibility: public -/
@[reducible, rust_type "nist_drbg_rs::ctr::AesLimits"]
def nist_drbg_rs.ctr.AesLimits := Unit

/-- [mike_rs::elliptic::x_point::PointX]
    Source: 'src/elliptic/x_point.rs', lines 6:0-9:1
    Visibility: public -/
structure elliptic.x_point.PointX (Fq : Type) (Clause0_Encoded : Type) where
  X : Fq
  Z : Fq

/-- [mike_rs::elliptic::basis::BasisX]
    Source: 'src/elliptic/basis.rs', lines 6:0-10:1
    Visibility: public -/
structure elliptic.basis.BasisX (Fq : Type) (Clause0_Encoded : Type) where
  P : elliptic.x_point.PointX Fq Clause0_Encoded
  Q : elliptic.x_point.PointX Fq Clause0_Encoded
  PQ : elliptic.x_point.PointX Fq Clause0_Encoded

/-- [mike_rs::elliptic::curve::Curve]
    Source: 'src/elliptic/curve.rs', lines 6:0-9:1
    Visibility: public -/
structure elliptic.curve.Curve (Fq : Type) (Clause0_Encoded : Type) where
  A : Fq
  A24 : Fq

/-- [mike_rs::elliptic::jac_arithmetic::PointW]
    Source: 'src/elliptic/jac_arithmetic.rs', lines 10:0-15:1
    Visibility: public -/
structure elliptic.jac_arithmetic.PointW (Fq : Type) (Clause0_Encoded : Type)
  where
  X : Fq
  Y : Fq
  Z : Fq
  T : Fq

/-- [mike_rs::elliptic::jac_point::Point]
    Source: 'src/elliptic/jac_point.rs', lines 9:0-13:1
    Visibility: public -/
structure elliptic.jac_point.Point (Fq : Type) (Clause0_Encoded : Type) where
  X : Fq
  Y : Fq
  Z : Fq

/-- [mike_rs::theta::dim_two::ThetaPointDimTwo]
    Source: 'src/theta/dim_two.rs', lines 5:0-10:1
    Visibility: public -/
structure theta.dim_two.ThetaPointDimTwo (Fp : Type) (Clause0_Encoded : Type)
  where
  x : Fp
  y : Fp
  z : Fp
  t : Fp

/-- [mike_rs::gluing::diagonal_gluing::DiagonalImages]
    Source: 'src/gluing/diagonal_gluing.rs', lines 5:0-9:1
    Visibility: public -/
structure gluing.diagonal_gluing.DiagonalImages (Fp : Type) (Clause0_Encoded :
  Type) where
  gluing_kernel : Array (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize) 4#usize
  image_plus : alloc.vec.Vec (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize)
  image_minus : alloc.vec.Vec (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize)

/-- [mike_rs::theta::dim_two::ThetaStructureDimTwo]
    Source: 'src/theta/dim_two.rs', lines 161:0-163:1
    Visibility: public -/
structure theta.dim_two.ThetaStructureDimTwo (Fp : Type) (Clause0_Encoded :
  Type) where
  null_point : theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded

/-- [mike_rs::gluing::scholten_gluing::ScholtenImages]
    Source: 'src/gluing/scholten_gluing.rs', lines 9:0-14:1
    Visibility: public -/
structure gluing.scholten_gluing.ScholtenImages (Fp : Type) (Clause0_Encoded :
  Type) where
  diagonal_kernel : Array (theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded)
    4#usize
  gluing_kernel : Array (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize) 3#usize
  image_plus : alloc.vec.Vec (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize)
  image_minus : alloc.vec.Vec (Array (theta.dim_two.ThetaPointDimTwo Fp
    Clause0_Encoded) 2#usize)

/-- [mike_rs::gluing::diagonal_gluing::diagonal_isogeny::{closure#1}]
    Source: 'src/gluing/diagonal_gluing.rs', lines 54:17-54:63 -/
def gluing.diagonal_gluing.diagonal_isogeny.closure_1 (Fp : Type)
  (Clause0_Encoded : Type) :=
  alloc.vec.Vec (theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded) ×
  Std.Usize × alloc.vec.Vec (theta.dim_two.ThetaPointDimTwo Fp
  Clause0_Encoded)

/-- [mike_rs::gluing::diagonal_gluing::diagonal_isogeny::{closure}]
    Source: 'src/gluing/diagonal_gluing.rs', lines 52:31-52:69 -/
def gluing.diagonal_gluing.diagonal_isogeny.closure (Fp : Type)
  (Clause0_Encoded : Type) :=
  alloc.vec.Vec (theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded) ×
  alloc.vec.Vec (theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded)

/-- [mike_rs::theta::dim_four::ThetaPoint]
    Source: 'src/theta/dim_four.rs', lines 7:0-9:1
    Visibility: public -/
structure theta.dim_four.ThetaPoint (Fq : Type) (Clause0_Encoded : Type) where
  coords : Array Fq 16#usize

/-- [mike_rs::theta::dim_four::ThetaPointCompressed]
    Source: 'src/theta/dim_four.rs', lines 240:0-242:1
    Visibility: public -/
structure theta.dim_four.ThetaPointCompressed (Fq : Type) (Clause0_Encoded :
  Type) where
  coords : Array Fq 10#usize

/-- [mike_rs::theta::dim_four::ThetaStructure]
    Source: 'src/theta/dim_four.rs', lines 441:0-445:1
    Visibility: public -/
structure theta.dim_four.ThetaStructure (Fq : Type) (Clause0_Encoded : Type)
  where
  null_point : theta.dim_four.ThetaPoint Fq Clause0_Encoded
  inv_null_point : theta.dim_four.ThetaPoint Fq Clause0_Encoded
  inv_null_point_dual_sq : theta.dim_four.ThetaPoint Fq Clause0_Encoded

/-- [mike_rs::gluing::dim_four_gluing::dim_four_gluing_isogeny::{closure#2}]
    Source: 'src/gluing/dim_four_gluing.rs', lines 186:13-194:9 -/
@[reducible]
def gluing.dim_four_gluing.dim_four_gluing_isogeny.closure_2 (Fp : Type)
  (Clause0_Encoded : Type) :=
  theta.dim_four.ThetaPoint Fp Clause0_Encoded

/-- [mike_rs::gluing::dim_four_gluing::dim_four_gluing_isogeny::{closure#1}]
    Source: 'src/gluing/dim_four_gluing.rs', lines 170:58-170:93 -/
@[reducible]
def gluing.dim_four_gluing.dim_four_gluing_isogeny.closure_1 (Fp : Type)
  (Clause0_Encoded : Type) :=
  theta.dim_four.ThetaPoint Fp Clause0_Encoded

/-- [mike_rs::gluing::dim_four_gluing::dim_four_gluing_isogeny::{closure}]
    Source: 'src/gluing/dim_four_gluing.rs', lines 160:79-165:5 -/
@[reducible]
def gluing.dim_four_gluing.dim_four_gluing_isogeny.closure (Fp : Type)
  (Clause0_Encoded : Type) :=
Unit

/-- [mike_rs::mike::mike_impl::KernelPoints]
    Source: 'src/mike/mike_impl.rs', lines 233:0-237:1
    Visibility: public -/
structure mike.mike_impl.KernelPoints (Fp2 : Type) (Clause0_BaseField : Type)
  (Clause0_Clause0_Encoded : Type) (Clause0_Clause1_Clause0_Encoded : Type)
  (Clause0_Clause2_Clause0_Encoded : Type) (Clause0_Clause3_Clause0_Encoded :
  Type) (Clause0_Clause4_Encoded : Type) where
  scholten_kernel : Array (elliptic.jac_point.Point Fp2
    Clause0_Clause0_Encoded) 2#usize
  diagonal_kernel : Array (elliptic.jac_point.Point Fp2
    Clause0_Clause0_Encoded) 2#usize
  gluing_kernel : Array (Array (elliptic.jac_point.Point Fp2
    Clause0_Clause0_Encoded) 2#usize) 3#usize

/-- [mike_rs::gluing::scholten_gluing::ScholtenContext]
    Source: 'src/gluing/scholten_gluing.rs', lines 16:0-20:1
    Visibility: public -/
structure gluing.scholten_gluing.ScholtenContext (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) where
  shift : elliptic.jac_point.Point Fp2 Clause1_Clause0_Encoded
  precomp : Array Fp 5#usize
  J : theta.dim_two.ThetaPointDimTwo Fp Clause0_Encoded

/-- [mike_rs::gluing::scholten_gluing::scholten_isogeny::{closure#2}]
    Source: 'src/gluing/scholten_gluing.rs', lines 319:13-324:9 -/
def gluing.scholten_gluing.scholten_isogeny.closure_2 (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) :=
  elliptic.curve.Curve Fp2 Clause1_Clause0_Encoded × Array
  (elliptic.jac_point.Point Fp2 Clause1_Clause0_Encoded) 2#usize ×
  gluing.scholten_gluing.ScholtenContext Fp Fp2 Clause0_Encoded
  Clause1_Clause0_Encoded Clause1_Clause1_Clause0_Encoded
  Clause1_Clause2_Clause0_Encoded Clause1_Clause3_Clause0_Encoded
  Clause1_Clause4_Encoded

/-- [mike_rs::gluing::scholten_gluing::scholten_isogeny::{closure#1}]
    Source: 'src/gluing/scholten_gluing.rs', lines 309:13-314:9 -/
def gluing.scholten_gluing.scholten_isogeny.closure_1 (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) :=
  elliptic.curve.Curve Fp2 Clause1_Clause0_Encoded × Array
  (elliptic.jac_point.Point Fp2 Clause1_Clause0_Encoded) 2#usize ×
  gluing.scholten_gluing.ScholtenContext Fp Fp2 Clause0_Encoded
  Clause1_Clause0_Encoded Clause1_Clause1_Clause0_Encoded
  Clause1_Clause2_Clause0_Encoded Clause1_Clause3_Clause0_Encoded
  Clause1_Clause4_Encoded

/-- [mike_rs::gluing::scholten_gluing::scholten_isogeny::{closure}]
    Source: 'src/gluing/scholten_gluing.rs', lines 292:32-292:48 -/
@[reducible]
def gluing.scholten_gluing.scholten_isogeny.closure (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) :=
Unit

/-- [mike_rs::gluing::scholten_gluing::apply_scholten_isogeny::{closure}::{closure}]
    Source: 'src/gluing/scholten_gluing.rs', lines 248:28-248:86 -/
def gluing.scholten_gluing.apply_scholten_isogeny.closure.closure (Fp : Type)
  (Fp2 : Type) (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) (N : Std.Usize) (M : Std.Usize) :=
  elliptic.curve.Curve Fp2 Clause1_Clause0_Encoded ×
  gluing.scholten_gluing.ScholtenContext Fp Fp2 Clause0_Encoded
  Clause1_Clause0_Encoded Clause1_Clause1_Clause0_Encoded
  Clause1_Clause2_Clause0_Encoded Clause1_Clause3_Clause0_Encoded
  Clause1_Clause4_Encoded × Bool

/-- [mike_rs::gluing::scholten_gluing::apply_scholten_isogeny::{closure}]
    Source: 'src/gluing/scholten_gluing.rs', lines 248:14-248:87 -/
def gluing.scholten_gluing.apply_scholten_isogeny.closure (Fp : Type) (Fp2 :
  Type) (Clause0_Encoded : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) (N : Std.Usize) (M : Std.Usize) :=
  elliptic.curve.Curve Fp2 Clause1_Clause0_Encoded ×
  gluing.scholten_gluing.ScholtenContext Fp Fp2 Clause0_Encoded
  Clause1_Clause0_Encoded Clause1_Clause1_Clause0_Encoded
  Clause1_Clause2_Clause0_Encoded Clause1_Clause3_Clause0_Encoded
  Clause1_Clause4_Encoded × Bool

/-- [mike_rs::mike::mike_impl::MikeConstants]
    Source: 'src/mike/mike_impl.rs', lines 11:0-15:1
    Visibility: public -/
structure mike.mike_impl.MikeConstants where
  f : Std.Usize
  c : Std.Usize
  e : Std.Usize

/-- [mike_rs::mike::mike_impl::MikeParameters]
    Source: 'src/mike/mike_impl.rs', lines 25:0-29:1
    Visibility: public -/
structure mike.mike_impl.MikeParameters (Fq : Type) (Clause0_BaseField : Type)
  (Clause0_Clause0_Encoded : Type) (Clause0_Clause1_Clause0_Encoded : Type)
  (Clause0_Clause2_Clause0_Encoded : Type) (Clause0_Clause3_Clause0_Encoded :
  Type) (Clause0_Clause4_Encoded : Type) where
  constants : mike.mike_impl.MikeConstants
  starting_curve : elliptic.curve.Curve Fq Clause0_Clause0_Encoded
  basis : elliptic.basis.BasisX Fq Clause0_Clause0_Encoded

/-- [mike_rs::mike::mike_impl::MikeError]
    Source: 'src/mike/mike_impl.rs', lines 50:0-56:1
    Visibility: public -/
@[discriminant isize]
inductive mike.mike_impl.MikeError where
| InvalidPublicKeyEncoding : mike.mike_impl.MikeError
| UnsupportedPublicKey : mike.mike_impl.MikeError
| NonSupersingularPublicKey : mike.mike_impl.MikeError
| NonCanonicalPublicKey : mike.mike_impl.MikeError
| RngFailure : mike.mike_impl.MikeError

/-- [mike_rs::mike::mike_impl::MikePublicKey]
    Source: 'src/mike/mike_impl.rs', lines 60:0-62:1
    Visibility: public -/
structure mike.mike_impl.MikePublicKey (Fq : Type) (Clause0_BaseField : Type)
  (Clause0_Clause0_Encoded : Type) (Clause0_Clause1_Clause0_Encoded : Type)
  (Clause0_Clause2_Clause0_Encoded : Type) (Clause0_Clause3_Clause0_Encoded :
  Type) (Clause0_Clause4_Encoded : Type) where
  curve : elliptic.curve.Curve Fq Clause0_Clause0_Encoded

/-- [mike_rs::mike::mike_impl::MikePrivateKey]
    Source: 'src/mike/mike_impl.rs', lines 113:0-118:1
    Visibility: public -/
structure mike.mike_impl.MikePrivateKey (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_BaseField : Type) (Clause1_Clause0_Encoded
  : Type) (Clause1_Clause1_Clause0_Encoded : Type)
  (Clause1_Clause2_Clause0_Encoded : Type) (Clause1_Clause3_Clause0_Encoded :
  Type) (Clause1_Clause4_Encoded : Type) (N : Std.Usize) where
  _phantom_fp : core.marker.PhantomData Fp
  _phantom_fp2 : core.marker.PhantomData Fp2
  constants : mike.mike_impl.MikeConstants
  secret : Array Std.U8 N

/-- [mike_rs::mike::mike_impl::Mike]
    Source: 'src/mike/mike_impl.rs', lines 135:0-138:1
    Visibility: public -/
structure mike.mike_impl.Mike (Fp : Type) (Fp2 : Type) (Clause0_Encoded : Type)
  (Clause1_BaseField : Type) (Clause1_Clause0_Encoded : Type)
  (Clause1_Clause1_Clause0_Encoded : Type) (Clause1_Clause2_Clause0_Encoded :
  Type) (Clause1_Clause3_Clause0_Encoded : Type) (Clause1_Clause4_Encoded :
  Type) (N : Std.Usize) where
  _phantom_fp : core.marker.PhantomData Fp
  params : mike.mike_impl.MikeParameters Fp2 Clause1_BaseField
    Clause1_Clause0_Encoded Clause1_Clause1_Clause0_Encoded
    Clause1_Clause2_Clause0_Encoded Clause1_Clause3_Clause0_Encoded
    Clause1_Clause4_Encoded

/-- [mike_rs::mike::mike_impl::{mike_rs::mike::mike_impl::Mike<Fp, Fp2, Clause0_Encoded, Clause1_BaseField, Clause1_Clause0_Encoded, Clause1_Clause1_Clause0_Encoded, Clause1_Clause2_Clause0_Encoded, Clause1_Clause3_Clause0_Encoded, Clause1_Clause4_Encoded, N>}::generate_scalar::{closure}]
    Source: 'src/mike/mike_impl.rs', lines 171:21-171:46 -/
@[reducible]
def mike.mike_impl.Mike.generate_scalar.closure (Fp : Type) (Fp2 : Type) (R :
  Type) (Clause0_Encoded : Type) (Clause1_BaseField : Type)
  (Clause1_Clause0_Encoded : Type) (Clause1_Clause1_Clause0_Encoded : Type)
  (Clause1_Clause2_Clause0_Encoded : Type) (Clause1_Clause3_Clause0_Encoded :
  Type) (Clause1_Clause4_Encoded : Type) (Clause2_Error : Type)
  (Clause3_Clause0_Error : Type) (N : Std.Usize) :=
Unit

/-- [mike_rs::mike::mike_impl::{mike_rs::mike::mike_impl::Mike<Fp, Fp2, Clause0_Encoded, Clause1_BaseField, Clause1_Clause0_Encoded, Clause1_Clause1_Clause0_Encoded, Clause1_Clause2_Clause0_Encoded, Clause1_Clause3_Clause0_Encoded, Clause1_Clause4_Encoded, N>}::keygen_seeded::{closure}]
    Source: 'src/mike/mike_impl.rs', lines 225:69-225:94 -/
@[reducible]
def mike.mike_impl.Mike.keygen_seeded.closure (Fp : Type) (Fp2 : Type)
  (Clause0_Encoded : Type) (Clause1_BaseField : Type) (Clause1_Clause0_Encoded
  : Type) (Clause1_Clause1_Clause0_Encoded : Type)
  (Clause1_Clause2_Clause0_Encoded : Type) (Clause1_Clause3_Clause0_Encoded :
  Type) (Clause1_Clause4_Encoded : Type) (N : Std.Usize) :=
Unit

/-- [mike_rs::theta::modular_invariants::{mike_rs::theta::dim_four::ThetaStructure<Fq, Clause0_Encoded>}::absolute_modular_invariants::{closure}]
    Source: 'src/theta/modular_invariants.rs', lines 68:56-74:9 -/
@[reducible]
def theta.modular_invariants.ThetaStructure.absolute_modular_invariants.closure
  (Fq : Type) (Clause0_Encoded : Type) :=
Unit

end mike_rs
