-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mike_rs]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::array::iter::IntoIter]
    Source: '/rustc/library/core/src/array/iter.rs', lines 20:0-20:38
    Name pattern: [core::array::iter::IntoIter]
    Visibility: public -/
@[rust_type "core::array::iter::IntoIter"]
axiom core.array.iter.IntoIter (T : Type) (N : Std.Usize) : Type

/-- [aes::soft::Aes256]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aes-0.8.4/src/soft.rs', lines 42:8-44:9
    Name pattern: [aes::soft::Aes256]
    Visibility: public -/
@[rust_type "aes::soft::Aes256"]
axiom aes.soft.Aes256 : Type

/-- [typenum::uint::UInt]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 148:0-148:21
    Name pattern: [typenum::uint::UInt]
    Visibility: public -/
@[rust_type "typenum::uint::UInt"]
axiom typenum.uint.UInt (U : Type) (B : Type) : Type

/-- [generic_array::GenericArrayImplOdd]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 148:0-148:36
    Name pattern: [generic_array::GenericArrayImplOdd]
    Visibility: public -/
@[rust_type "generic_array::GenericArrayImplOdd"]
axiom generic_array.GenericArrayImplOdd (T : Type) (U : Type) : Type

/-- [generic_array::GenericArrayImplEven]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 126:0-126:37
    Name pattern: [generic_array::GenericArrayImplEven]
    Visibility: public -/
@[rust_type "generic_array::GenericArrayImplEven"]
axiom generic_array.GenericArrayImplEven (T : Type) (U : Type) : Type

/-- [generic_array::GenericArray]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 179:0-179:45
    Name pattern: [generic_array::GenericArray]
    Visibility: public -/
@[rust_type "generic_array::GenericArray"]
axiom generic_array.GenericArray (T : Type) (U : Type) (Clause0_ArrayType :
  Type) : Type

/-- [inout::inout::InOut]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/inout-0.1.4/src/inout.rs', lines 7:0-7:31
    Name pattern: [inout::inout::InOut]
    Visibility: public -/
@[rust_type "inout::inout::InOut" (mutRegions := #[1])]
axiom inout.inout.InOut (T : Type) : Type

/-- [nist_drbg_rs::ctr::CtrDrbg]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nist-drbg-rs-0.1.3/src/ctr.rs', lines 20:0-20:99
    Name pattern: [nist_drbg_rs::ctr::CtrDrbg]
    Visibility: public -/
@[rust_type "nist_drbg_rs::ctr::CtrDrbg"]
axiom nist_drbg_rs.ctr.CtrDrbg (C : Type) (L : Type) (Clause0_Clause0_BlockSize
  : Type) (Clause0_Clause0_Clause0_ArrayType : Type) (Clause1_Clause0_KeySize :
  Type) (Clause1_Clause0_Clause0_ArrayType : Type) (Clause2_Clause0_BlockSize :
  Type) (Clause2_Clause0_Clause0_ArrayType : Type) (SEEDLEN : Std.Usize) : Type

/-- [nist_drbg_rs::Policy]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nist-drbg-rs-0.1.3/src/lib.rs', lines 189:0-189:17
    Name pattern: [nist_drbg_rs::Policy]
    Visibility: public -/
@[rust_type "nist_drbg_rs::Policy"]
axiom nist_drbg_rs.Policy : Type

/-- [mike_rs::fields::MikeIFp2]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp2_gen.rs', lines 91:8-94:9
    Visibility: public -/
axiom fields.MikeIFp2 : Type

/-- [mike_rs::fields::MikeIIIFp2]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp2_gen.rs', lines 91:8-94:9
    Visibility: public -/
axiom fields.MikeIIIFp2 : Type

/-- [mike_rs::fields::MikeVFp2]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp2_gen.rs', lines 91:8-94:9
    Visibility: public -/
axiom fields.MikeVFp2 : Type

/-- [mike_rs::fields::MikeIFp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp_gen.rs', lines 41:8-41:50
    Visibility: public -/
axiom fields.MikeIFp : Type

/-- [mike_rs::fields::MikeIIIFp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp_gen.rs', lines 41:8-41:50
    Visibility: public -/
axiom fields.MikeIIIFp : Type

/-- [mike_rs::fields::MikeVFp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fp2-0.5.1/src/fp_gen.rs', lines 41:8-41:50
    Visibility: public -/
axiom fields.MikeVFp : Type

